apiVersion: batch/v1 
kind: CronJob 
metadata: 
  name: elasticsearch-backup 
spec: 
  schedule: "0 0 * * *" 
  jobTemplate: 
    spec: 
      template: 
        spec: 
          restartPolicy: OnFailure
          containers: 
          - name: backup-container 
            image: backup-image:tag 
            volumeMounts: 
            - name: es-snapshot-config 
              mountPath: /etc/elasticsearch 
          volumes: 
          - name: es-snapshot-config 
            configMap: 
              name: es-snapshot-config 
